# Generated by Django 4.2.5 on 2023-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_date_of_birth_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True, verbose_name='ادرس ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=1, max_length=50, verbose_name='نام و نام خوانوادگی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
