# Generated by Django 4.2.5 on 2023-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_email_user_fullname_alter_user_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('code', models.SmallIntegerField(verbose_name='کد تایید')),
                ('expiration_data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انفضل')),
            ],
            options={
                'verbose_name': 'اعتبار سنجی ',
                'verbose_name_plural': 'اعتبار سنجی ها',
            },
        ),
    ]
